# 1. https://docs.gitea.com/installation/install-with-docker
---
version: "3"

networks:
  gitea:
    external: false
  traefik-proxy:
    driver: overlay
    attachable: true
    external: true

services:

  server:
    image: gitea/gitea:@version@
    container_name: "gitea-1"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - traefik-proxy
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    #labels:
      #- 
