# Gitea service representation as Docker containers
#
# This file includes a complete setup of Gitea [1],
# MySQL [2], and OpenGists [8]. Someday, perhaps also a
# Pages server via Codeberg Pages [7].
#
# SEE ALSO
#
# 1. https://docs.gitea.com/installation/install-with-docker
# 2. https://docs.gitea.com/installation/database-prep
# 3. https://docs.gitea.com/administration/repo-indexer
# 4. https://docs.gitea.com/administration/customizing-gitea
# 5. https://docs.gitea.com/administration/external-renderers
# 6. https://git.jonasfranz.software/JonasFranzDEV/gitea-github-migrator
# 7. https://docs.codeberg.org/codeberg-pages/
# OPENGIST
# 8. https://github.com/thomiceli/opengist/blob/master/docs/installation.md
# 9. https://github.com/thomiceli/opengist/tree/master
# 10. https://github.com/thomiceli/opengist/blob/master/docs/configuration/index.md#configuration
#
---
# version: "3"

networks:
  gitea:
    external: false
  traefik-proxy:
    driver: overlay
    attachable: true
    external: true

volumes:
  gitea_config:
    driver: local
  # git repositories
  gitea_data:
    driver: local
  # database used by gitea
  mysql:
    driver: local
  # repositories
  opengist_data:
    driver: local

services:
  server:
    # https://hub.docker.com/r/gitea/gitea/tags
    image: "gitea/gitea:1.22.1"
    container_name: "gitea-1"
    restart: always
    hostname: "gitea"
    #user: "1000:1000"  # id -u git
    depends_on:
      - db
      - opengist
    networks:
      - traefik-proxy
      - gitea
    ports:
      - "3000:3000"  # gitea serve
      - "222:22"  # SSH
      # - "127.0.0.1:2222:22"
    env_file:
      - ".env"
      - ".env.secrets"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__security__SECRET_KEY=[value returned by generate secret SECRET_KEY]
      - GITEA__security__INTERNAL_TOKEN=[value returned by generate secret INTERNAL_TOKEN]
    volumes:
      # bind mounts
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./scripts:/scripts:ro"
      # gitea config
      - "./mounts/config/gitea:/var/lib/gitea/custom:rw"
      # volume mounts
      # - gitea_config:/var/lib/gitea/custom
      # git repos
      - gitea_data:/var/lib/gitea
      #- gitea_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.rule=Host(`git.fs1.home`) && PathPrefix(`/`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.routers.gitea.tls.certresolver=staging-web-acme"
      - "traefik.http.routers.gitea.service=gitea"
      #
      - "homepage.group=syn"
      - "homepage.name=gitea-1"
      - "homepage.siteMonitor=http://docker.fs1.home:3000/"
      - "homepage.ping=docker.fs1.home"
  db:
    image: "mysql:8"
    container_name: "db-gitea-1"
    hostname: "db"
    restart: unless-stopped
    env_file:
      - ".env"
      - ".env.secrets"
    ports:
      - "3306:3306"  # mysqld
      #- "127.0.0.1:3306:3306"  # mysqld
    networks:
      - gitea
      #- traefik-proxy
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./mounts/config/mysql/my.cnf:/etc/my.cnf:ro"
      - "./mounts/config/mysql/ssl:/etc/mysql/ssl:ro"
      - mysql:/var/lib/mysql
    labels:
      - "traefik.enable=false"
  opengist:
    image: "ghcr.io/thomiceli/opengist:1"
    container_name: "opengist-gitea-1"
    hostname: "opengist"
    restart: unless-stopped
    networks:
      - gitea
      - traefik-proxy
    ports:
      - "3001:6157"  # HTTP
      - "2222:2222"  # SSH
    volumes:
      # bind mounts
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./scripts:/scripts:ro"
      - "./mounts/config/gist/config.yml:/config.yml:ro"
      # TODO(JEFF): LOGS
      #- ./mounts/logs/gist/opengist.log
      # named volumes
      - opengist_data:/opengist
    env_file:
      - ".env"
      - ".env.secrets"
    environment:
      UID: 1000  # git
      GID: 1000  # :git
      OG_LOG_LEVEL: "info"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gist.entrypoints=websecure"
      - "traefik.http.routers.gist.rule=Host(`gist.fs1.home`) && PathPrefix(`/`)"
      - "traefik.http.services.gist.loadbalancer.server.port=6157"
      - "traefik.http.routers.gist.tls.certresolver=staging-web-acme"
      - "traefik.http.routers.gist.service=gist"
      #
      - "homepage.group=syn"
      - "homepage.name=opengist-gitea-1"
      - "homepage.siteMonitor=http://docker.fs1.home:3001/"
      - "homepage.ping=docker.fs1.home"
  jenkins:
    restart: unless-stopped
    image: "jenkins:2.7.4-alpine"
    hostname: "jenkins"
    container_name: "jenkins-gitea-1"
    ports:
      - "3002:8080" # HTTP
      - "2244:22"  # SSH (optional)
    networks:
      - gitea
      - traefik-proxy
    env_file:
      - ".env"
      - ".env.secrets"
    volumes:
      # bind mounts
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./scripts:/scripts:ro"
      #- "./mounts/config/jenkins:/config:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.rule=Host(`buildbox.fs1.home`) && PathPrefix(`/`)"
      # Host(`buildbox-1.fs1.home`) && PathPrefix(`/`)
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.http.routers.jenkins.tls.certresolver=staging-web-acme"
      - "traefik.http.routers.jenkins.service=jenkins"
      #
      - "homepage.group=syn"
      - "homepage.name=jenkins-gitea-1"
      - "homepage.siteMonitor=http://docker.fs1.home:3002/"
      - "homepage.ping=docker.fs1.home"
    environment:
      - "JAVA_OPTS=-Xmx256m -Dhudson.DNSMultiCast.disabled=true"
    expose:
      - "8080"
