# 1. https://docs.gitea.com/installation/install-with-docker
#
# docker run -it --rm gitea/gitea:1 gitea generate secret SECRET_KEY
# docker run -it --rm  gitea/gitea:1 gitea generate secret INTERNAL_TOKEN
#
---
#version: "3"

networks:
  gitea:
    external: false
  traefik-proxy:
    driver: overlay
    attachable: true
    external: true
    
volumes:
  gitea_config:
    driver: local
  gitea_data:
    driver: local
  mysql:
    driver: local

services:
  server:
    image: gitea/gitea:@version@
    container_name: "gitea-1"
    restart: always
    # 1. https://docs.gitea.com/installation/install-with-docker-rootless#custom-user
    user: "1001" # id -u git
    depends_on:
      - db
      - opengist
    networks:
      - traefik-proxy
      - gitea
    ports:
      # gitea serve
      - "3000:3000"
      # SSH
      - "222:22"
      #- "127.0.0.1:2222:22"
    env_file:
      - ".env"
      - ".env.secrets"
    environment:
      - TZ=America/Chicago
      - LC_TIME=C.UTF-8
      - LANG=en_US.UTF-8
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__FROM=${GITEA__mailer__FROM:?GITEA__mailer__FROM not set}
      - GITEA__mailer__PROTOCOL=smtps
      - GITEA__mailer__SMTP_ADDR=${GITEA__mailer__SMTP_ADDR:?GITEA__mailer__SMTP_ADDR not set}
      - GITEA__mailer__SMTP_PORT=${GITEA__mailer__SMTP_PORT:?GITEA__mailer__SMTP_PORT not set}
      - GITEA__mailer__USER=${GITEA__mailer__USER:-apikey}
      - GITEA__mailer__PASSWD="""${GITEA__mailer__PASSWD:?GITEA__mailer__PASSWD not set}"""
      - GITEA__security__SECRET_KEY=[value returned by generate secret SECRET_KEY]
      - GITEA__security__INTERNAL_TOKEN=[value returned by generate secret INTERNAL_TOKEN]
    volumes:
      # bind mounts
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # gitea config
      - "./mounts/config:/var/lib/gitea/custom:rw"
      # volume mounts
      #- gitea_config:/var/lib/gitea/custom
      # git repos
      - gitea_data:/var/lib/gitea
  db:
    image: "mysql:8"
    restart: always
    env_file:
      - ".env"
      - ".env.secrets"
    networks:
      - gitea
    volumes:
      - mysql:/var/lib/mysql
  # 1. https://github.com/thomiceli/opengist/blob/master/docs/installation.md
  opengist:
    image: "ghcr.io/thomiceli/opengist:1"
    container_name: "opengist-1"
    restart: unless-stopped
    networks:
      - gitea
      - traefik-proxy
    ports:
      - "6157:6157" # HTTP port
      - "2222:2222" # SSH port, can be removed if you don't use SSH
    volumes:
      - "$HOME/.opengist:/opengist"
    env_file:
      - ".env"
      - ".env.secrets"
    environment:
      UID: 1001 # git
      GID: 1001 # :git
