# 1. https://docs.gitea.com/installation/install-with-docker
#
# docker run -it --rm gitea/gitea:1 gitea generate secret SECRET_KEY
# docker run -it --rm  gitea/gitea:1 gitea generate secret INTERNAL_TOKEN
#
---
#version: "3"

networks:
  gitea:
    external: false
  traefik-proxy:
    driver: overlay
    attachable: true
    external: true
    
volumes:
  gitea_config:
    driver: local
  gitea_data:
    driver: local
  mysql:
    driver: local

services:
  server:
    image: gitea/gitea:@version@
    container_name: "gitea-1"
    restart: always
    # 1. https://docs.gitea.com/installation/install-with-docker-rootless#custom-user
    user: "1001" # id -u git
    depends_on:
      - db
    networks:
      - traefik-proxy
      - gitea
    ports:
      # gitea serve
      - "3000:3000"
      # SSH
      - "222:22"
      #- "127.0.0.1:2222:22"
    environment:
      - TZ=America/Chicago
      - LC_TIME=C.UTF-8
      - LANG=en_US.UTF-8
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__FROM=${GITEA__mailer__FROM:?GITEA__mailer__FROM not set}
      - GITEA__mailer__PROTOCOL=smtps
      - GITEA__mailer__SMTP_ADDR=${GITEA__mailer__SMTP_ADDR:?GITEA__mailer__SMTP_ADDR not set}
      - GITEA__mailer__SMTP_PORT=${GITEA__mailer__SMTP_PORT:?GITEA__mailer__SMTP_PORT not set}
      - GITEA__mailer__USER=${GITEA__mailer__USER:-apikey}
      - GITEA__mailer__PASSWD="""${GITEA__mailer__PASSWD:?GITEA__mailer__PASSWD not set}"""
      - GITEA__security__SECRET_KEY=[value returned by generate secret SECRET_KEY]
      - GITEA__security__INTERNAL_TOKEN=[value returned by generate secret INTERNAL_TOKEN]
    volumes:
      # gitea config
      - "./mounts/config:/data:rw"
      #- gitea_config:/data
      # git repos
      - gitea_data:/var/lib/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - mysql:/var/lib/mysql
