# 0. https://hub.docker.com/r/gitea/gitea/tags
# 1. https://docs.gitea.com/installation/install-with-docker
# 2. https://docs.gitea.com/administration/repo-indexer
# 3. https://docs.gitea.com/administration/customizing-gitea
# 4. https://docs.gitea.com/administration/external-renderers
# docker run -it --rm gitea/gitea:1 gitea generate secret SECRET_KEY
# docker run -it --rm  gitea/gitea:1 gitea generate secret INTERNAL_TOKEN
#
---
# version: "3"

networks:
  gitea:
    external: false
  traefik-proxy:
    driver: overlay
    attachable: true
    external: true

volumes:
  gitea_config:
    driver: local
  # git repositories
  gitea_data:
    driver: local
  # database used by gitea
  mysql:
    driver: local
  opengist_config:
    driver: local

services:
  server:
    image: "gitea/gitea:1.22.1"
    container_name: "gitea-1"
    restart: always
    hostname: "gitea"
    # 1. https://docs.gitea.com/installation/install-with-docker-rootless#custom-user
    #user: "1000:1000"  # id -u git
    depends_on:
      - db
      - opengist
    networks:
      - traefik-proxy
      - gitea
    ports:
      # gitea serve
      - "3000:3000"
      # SSH
      - "222:22"
      # - "127.0.0.1:2222:22"
    env_file:
      - ".env"
      - ".env.secrets"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__mailer__ENABLED=true
      - GITEA__security__SECRET_KEY=[value returned by generate secret SECRET_KEY]
      - GITEA__security__INTERNAL_TOKEN=[value returned by generate secret INTERNAL_TOKEN]
    volumes:
      # bind mounts
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # gitea config
      - "./mounts/config:/var/lib/gitea/custom:rw"
      # volume mounts
      # - gitea_config:/var/lib/gitea/custom
      # git repos
      - gitea_data:/var/lib/gitea
  # 1. https://docs.gitea.com/installation/database-prep
  db:
    image: "mysql:8"
    container_name: "db-gitea-1"
    hostname: "db"
    restart: on-failure:2
    env_file:
      - ".env"
      - ".env.secrets"
    ports:
      - "3306:3306"
      #- "127.0.0.1:3306:3306"
    networks:
      - gitea
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./mounts/config/mysql/my.cnf:/etc/my.cnf:ro"
      - "./mounts/config/mysql/ssl:/etc/mysql/ssl:ro"
      - mysql:/var/lib/mysql
  # 1. https://github.com/thomiceli/opengist/blob/master/docs/installation.md
  opengist:
    image: "ghcr.io/thomiceli/opengist:1"
    container_name: "opengist-gitea-1"
    hostname: "opengist"
    restart: unless-stopped
    networks:
      - gitea
      - traefik-proxy
    ports:
      - "6157:6157"  # HTTP port
      - "2222:2222"  # SSH port, can be removed if you don't use SSH
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - "/etc/localtime:/etc/localtime:ro"
      - opengist_config:/config
      # repositories
      - gitea_data:/opengist
    env_file:
      - ".env"
      - ".env.secrets"
    environment:
      UID: 1000  # git
      GID: 1000  # :git
  # 1. https://codeberg.org/Codeberg/pages-server/src/branch/main
  # pages:
    # image:
  
